keywords = c(
"builders",
"engineered timber",
"downsize",
"council",
"solar system",
"Macadamia",
"miele",
"laminate",
"penthouse",
"asset",
"flexi apartments",
"lakeside",
"NBN",
"extend",
"builder",
"SMSF",
"summer house",
"stair",
"Interest Rate",
"frigidaire",
"pet friendly",
"kenwood",
"water view",
"rebuild",
"zero greenhouse",
"approved planning",
"vinyl",
"homeaway",
"downsizing",
"time share",
"double story",
"renovator",
"cottage",
"lodge",
"yield",
"heat recovery ventilation system",
"tiles",
"holiday home",
"stca",
"farm house",
"gas heating",
"tax",
"LPG",
"reserve bank",
"beachside",
"environmental sustainability",
"asko",
"community",
"weekender",
"downsizers",
"teen",
"gas",
"backyard",
"marble benchtop",
"luxury",
"gas kitchen",
"garage",
"delonghi",
"capital growth",
"trees",
"electric car",
"consolidate",
"fish tank",
"warehouse",
"rental yield",
"view",
"timber floors",
"fruit tree",
"carbon consumption",
"strata",
"granny flat",
"thermomix",
"vacation home",
"mirrors",
"lenders mortgage insurance",
"positive gearing",
"gas appliances",
"developers",
"fisher & paykel",
"student",
"superannuation",
"off the plan",
"knock down",
"solar panels",
"retirement village",
"eco friendly",
"elevator",
"extensive renovation",
"gas barbecue",
"eco housing",
"major renovation",
"timeshare",
"bosch",
"eco-friendly",
"waterfront",
"marble counter",
"university",
"restaurants",
"teenager",
"tax deduction",
"unfurnished",
"quartz",
"gas Miele",
"chalet",
"energy efficiency",
"NABER",
"tiny house",
"renovator's dream",
"tiled",
"open plan",
"retire",
"availability date",
"environmentally friendly",
"verandah",
"rba",
"gas heating bayonet",
"downsizer",
"linoleum",
"cashflow",
"DA approval",
"parking",
"aircon",
"debt consolidation",
"double glazed windows",
"senior living",
"investment",
"knockdown",
"nurse on site",
"sea change",
"laminate flooring",
"mirror",
"caeserstone",
"re-develop",
"Downturn",
"insurance",
"dacor",
"timber floorboards",
"swimming pool",
"investors",
"retreat",
"river",
"income",
"developer",
"solar",
"share",
"solid timber",
"gas appliance",
"villa",
"tennis court",
"pet-friendly",
"stayz",
"gas cooktop",
"nespresso",
"equity",
"gas bayonet",
"independent living",
"heritage",
"public transport",
"pool",
"gas outlets",
"balcony",
"caesarstone",
"dog friendly",
"school",
"refinance",
"glass",
"water tank",
"vacancy rate",
"gas outlet",
"hobby farm",
"bar",
"braun",
"senior communities",
"village bus",
"NBN ready",
"carpeted",
"wheelchair access",
"holiday letting",
"luxury appliance",
"ecofriendly",
"high school",
"build",
"country house",
"oak",
"chandelier",
"car space",
"fish pond",
"demolition",
"renovators dream",
"retirement communities",
"floorboards",
"teen retreat",
"tesla battery",
"invest",
"jenn-air",
"modern",
"dog park",
"physical asset",
"gas cooking",
"energy-efficient",
"pets allowed",
"photovoltaic",
"changeover costs",
"timber",
"subject to council approval",
"fujitsu",
"furnished",
"investor",
"Recession",
"self-managed super fund",
"bay",
"gas stove",
"airbnb",
"games room",
"dyson",
"assisted living",
"reserve bank of australia",
"cash rate",
"electrolux",
"extension",
"DIY",
"holiday park",
"refinancing",
"barbecue",
"park",
"gas fire",
"lift",
"floating floors",
"serviced apartment",
"guest occupation",
"vinyl flooring",
"renovation",
"negative gearing",
"over 55",
"waterside",
"SMEG",
"laminex",
"rate cut",
"self-sufficient",
"fruit",
"carpet",
"rental income",
"dishwasher")



supplement_property_details = function( cleaned_df ) {


# cleaned_df = cleaned_df %>% 
# head(100)

# for each keyword, create a new column with the keyword as the column name
# and the value as the number of times the keyword appears in the description

for ( keyword in keywords ) {
  cleaned_df[[keyword]] = grepl( keyword, cleaned_df$description_json, ignore.case = TRUE )
}

cleaned_df %>%
# head( 17 ) %>%
# tail( 1) %>%
#  pull( trackingData_json) %>%
# {.} -> x
mutate( tracking_data_keywords = map( trackingData_json, extract_trackingData)) %>%
unnest( tracking_data_keywords) 



}
